import type { EnemyDefinition } from "@imp/shared";

/** All enemy definitions indexed by ID */
export const ENEMIES: Record<string, EnemyDefinition> = {
  // ─── Goblin Woods (Tier 1) ──────────────────────────────
  goblin_grunt: {
    id: "goblin_grunt",
    name: "Goblin Grunt",
    hp: 10,
    attack: 4,
    defense: 0,
    speed: 3,
    luck: 0,
    attackRange: 1,
    minAttackRange: 1,
    requiresLineOfSight: false,
    aiType: "melee_aggressive",
    abilities: [],
    spriteKey: "goblin_grunt",
    materialDrops: { bones: 1 },
  },
  goblin_archer: {
    id: "goblin_archer",
    name: "Goblin Archer",
    hp: 7,
    attack: 5,
    defense: 0,
    speed: 4,
    luck: 1,
    attackRange: 5,
    minAttackRange: 2,
    requiresLineOfSight: false,
    aiType: "ranged_kite",
    abilities: [],
    spriteKey: "goblin_archer",
    materialDrops: { bones: 1 },
  },
  goblin_shaman: {
    id: "goblin_shaman",
    name: "Goblin Shaman",
    hp: 8,
    attack: 3,
    defense: 0,
    speed: 3,
    luck: 0,
    attackRange: 2,
    minAttackRange: 1,
    requiresLineOfSight: true,
    aiType: "support_heal",
    abilities: [],
    spriteKey: "goblin_shaman",
    materialDrops: { bones: 1 },
  },
  goblin_king: {
    id: "goblin_king",
    name: "Goblin King",
    hp: 35,
    attack: 7,
    defense: 2,
    speed: 4,
    luck: 1,
    attackRange: 1,
    minAttackRange: 1,
    requiresLineOfSight: false,
    aiType: "boss_custom",
    abilities: [],
    spriteKey: "goblin_king",
    isBoss: true,
    materialDrops: { bones: 3 },
  },

  // ─── Crystal Caves (Tier 2) ─────────────────────────────
  crystal_golem: {
    id: "crystal_golem",
    name: "Crystal Golem",
    hp: 18,
    attack: 6,
    defense: 2,
    speed: 2,
    luck: 0,
    attackRange: 1,
    minAttackRange: 1,
    requiresLineOfSight: false,
    aiType: "melee_aggressive",
    abilities: [],
    spriteKey: "crystal_golem",
    materialDrops: { stone: 2 },
  },
  cave_bat: {
    id: "cave_bat",
    name: "Cave Bat",
    hp: 8,
    attack: 6,
    defense: 0,
    speed: 6,
    luck: 2,
    attackRange: 2,
    minAttackRange: 1,
    requiresLineOfSight: false,
    aiType: "ranged_kite",
    abilities: [],
    spriteKey: "cave_bat",
    materialDrops: { bones: 1 },
  },
  gem_sprite: {
    id: "gem_sprite",
    name: "Gem Sprite",
    hp: 10,
    attack: 4,
    defense: 0,
    speed: 4,
    luck: 0,
    attackRange: 2,
    minAttackRange: 1,
    requiresLineOfSight: true,
    aiType: "support_heal",
    abilities: [],
    spriteKey: "gem_sprite",
    materialDrops: {},
  },
  crystal_wyrm: {
    id: "crystal_wyrm",
    name: "Crystal Wyrm",
    hp: 50,
    attack: 9,
    defense: 1,
    speed: 3,
    luck: 1,
    attackRange: 2,
    minAttackRange: 1,
    requiresLineOfSight: false,
    aiType: "boss_custom",
    abilities: [],
    spriteKey: "crystal_wyrm",
    isBoss: true,
    materialDrops: { stone: 4 },
  },

  // ─── Undead Crypt (Tier 3) ──────────────────────────────
  skeleton_warrior: {
    id: "skeleton_warrior",
    name: "Skeleton Warrior",
    hp: 14,
    attack: 7,
    defense: 1,
    speed: 4,
    luck: 0,
    attackRange: 1,
    minAttackRange: 1,
    requiresLineOfSight: false,
    aiType: "melee_aggressive",
    abilities: [],
    spriteKey: "skeleton_warrior",
    materialDrops: { bones: 2 },
  },
  bone_archer: {
    id: "bone_archer",
    name: "Bone Archer",
    hp: 9,
    attack: 8,
    defense: 0,
    speed: 5,
    luck: 2,
    attackRange: 5,
    minAttackRange: 2,
    requiresLineOfSight: false,
    aiType: "ranged_kite",
    abilities: [],
    spriteKey: "bone_archer",
    materialDrops: { bones: 2 },
  },
  necromancer: {
    id: "necromancer",
    name: "Necromancer",
    hp: 12,
    attack: 5,
    defense: 0,
    speed: 3,
    luck: 0,
    attackRange: 2,
    minAttackRange: 1,
    requiresLineOfSight: true,
    aiType: "support_heal",
    abilities: [],
    spriteKey: "necromancer",
    materialDrops: { bones: 1 },
  },
  lich_lord: {
    id: "lich_lord",
    name: "Lich Lord",
    hp: 65,
    attack: 11,
    defense: 2,
    speed: 3,
    luck: 2,
    attackRange: 2,
    minAttackRange: 1,
    requiresLineOfSight: false,
    aiType: "boss_custom",
    abilities: [],
    spriteKey: "lich_lord",
    isBoss: true,
    materialDrops: { bones: 4 },
  },
};

export function getEnemyDef(id: string): EnemyDefinition | undefined {
  return ENEMIES[id];
}
